package com.irfan.githubuser.model

data class DetailUser(
    val avatar_url: String? = "",
    val bio: String? = "",
    val blog: String? = "",
    val company: String? = "",
    val created_at: String? = "",
    val email: String? = "",
    val events_url: String? = "",
    val followers: Int? = -1,
    val followers_url: String? = "",
    val following: Int? = -1,
    val following_url: String? = "",
    val gists_url: String? = "",
    val gravatar_id: String? = "",
    val hireable: Boolean?,
    val html_url: String? = "",
    val id: Int? = -1,
    val location: String? = "",
    val login: String? = "",
    val name: String? = "",
    val node_id: String? = "",
    val organizations_url: String? = "",
    val public_gists: Int? = -1,
    val public_repos: Int? = -1,
    val received_events_url: String? = "",
    val repos_url: String? = "",
    val site_admin: Boolean? = null,
    val starred_url: String? = "",
    val subscriptions_url: String? = "",
    val twitter_username: Any? = "",
    val type: String? = "",
    val updated_at: String? = "",
    val url: String? = ""
)